name: Publish website

on:
  push:
    branches:
    - main

jobs:
  push_to_registry:
    name: Send website to rede linux
    runs-on: ubuntu-latest
    steps:
          
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: send website source over scp
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: renner
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          source: "index.html,etc/*"
          target: "/home/bmac/renner/www/MAC0499"
